FROM node:22-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.4 /lambda-adapter /opt/extensions/lambda-adapter
COPY --from=build /app/dist ./dist
COPY package.json ./
RUN npm install --omit=dev
ENV AWS_LWA_PORT=3007
EXPOSE 3007
CMD ["node", "dist/index.js"]
